using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DigitalArtistDatabase.Models
{
    public class Picture
    {
        public int ID { get; set; }
        //url is autogenerated
        public string ImageURL { get; set; }

        public int PostID { get; set; }

        public Post Post { get; set; }
    }
}